### ISSUE TITLE
[SRI] freddy's review from april 20th, 2015

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#280]
…sorted by sections:

These are mostly minor issues, so I can tackle them one-by-one with what I deem meaningful, but I'm happy to dive into a deeper discussion if someone is a bit more opinionated.

- [x] **1. Introduction**: *the scheme specified here applies to all HTML elements which trigger fetches* – I'd rewrite this to "can be applied". -- fixed in #299
- [x] **1.1 Goals:** The second goal (reporting) is somewhat unmatched, considering that we do not have reporting in either user agent. Though we do have this still in the spec (section 3.8) -- fixed in #285
- [x] **1.2.2 Resource integrity** Can we keep this document neutral and say "a browser's New Tab Page" instead of Chrome's? -- proposed in #304
- [x] **1.2.2 Resource integrity** The last bullet is also about reporting -- fixed in #285 and proposed complete removal in #298
- [ ] **3.1 Integrity metadata** example 3 - the hash is partially in bold text?
- [ ] **3.2 cryptographic functions** same here for example 4
- [ ] **3.3.5 Does *resource* match *metadataList*?**: should we really mandate that the `about:` scheme has always good integrity? It may be current practice, but I don't think we should rely on about things being from-disk content until eternity.
- [x] **3.6 the `integrity` attribute**: typo in the *Note*, s/make/may/ -- fixed in #297
- [x] move the ***in-spec* issues** to github and delete from the spec file. Issue 3, 13 and 17 (in 3.3.2,, 3.10 and 4) -- proposed in #305, #306 and #307

**Comment by fmarier** [comment]
I have no idea how to fix the broken markdown formatting in 3.1 and 3.2 :(

Regarding the about:scheme, let's discuss that in #319.

**Comment by fmarier** [comment]
I've moved the bold-in-hashes problems to #320.
